'use strict';

/**
 * @module Errors
 */
module.exports = {
    _required:          'required',
    _unknownField:      'unknown',
    equals:             'equals',
    contains:           'format',
    matches:            'format',
    isEmail:            'format',
    isURL:              'format',
    isFQDN:             'format',
    isIP:               'format',
    isAlpha:            'format',
    isNumeric:          'format',
    isAlphanumeric:     'format',
    isBase64:           'format',
    isHexadecimal:      'format',
    isLowercase:        'format',
    isUppercase:        'format',
    isInt:              'format',
    isFloat:            'format',
    isNull:             'format',
    isLength:           'length',
    isByteLength:       'length',
    isUUID:             'format',
    isDate:             'format',
    isAfter:            'format',
    isBefore:           'format',
    isIn:               'format',
    isCreditCard:       'format',
    isISBN:             'format',
    isMobilePhone:      'format',
    isJSON:             'format',
    isMultibyte:        'format',
    isAscii:            'format',
    isFullWidth:        'format',
    isHalfWidth:        'format',
    isVariableWidth:    'format',
    isSurrogatePair:    'format',
    isMongoId:          'format',
    isCurrency:         'format',
    toString:           null,
    toDate:             null,
    toFloat:            null,
    toInt:              null,
    toBoolean:          null,
    trim:               null,
    ltrim:              null,
    rtrim:              null,
    escape:             null,
    stripLow:           null,
    whitelist:          null,
    blacklist:          null,
    normalizeEmail:     null
};

